apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:  
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        preference:
          matchExpressions:
          - key: type
            operator: In
            values:
            - frontend
      - weight: 10
        preference:
          matchExpressions:
          - key: type
            operator: In
            values:
            - backend
  containers:
  - image: nginx
    name: nginx
    resources: {}