apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodename
  name: nodename
spec:
  nodeName: minikube-m03
  containers:
  - image: nginx
    name: nodename
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
