apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: buysboxenv
  name: buysboxenv
spec:
  containers:
  - command:
    - printenv
    image: busybox
    name: buysboxenv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
