apiVersion: v1
kind: Pod
metadata:
  name: commandtest
spec:
  containers:
  - name: commandtest
    image:  busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> ~/dates.txt; sleep 10; done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
