apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb-cs
  name: myweb-cs
spec:
  ports:
  - name: 80-32000
    port: 80
    protocol: TCP
    targetPort: 32000
  selector:
    app: myweb-cs
  type: ClusterIP
status:
  loadBalancer: {}
