apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostname
  name: hostname
spec:
  hostname: busybox-test
  hostAliases:
  - ip: "192.168.1.140"
    hostnames:
    - "test1.local"
    - "test2.local"
  containers:
  - image: busybox
    name: hostname
    command: ['hostname']
    env:
    - name: ENVTEST1
      value: "This is ENVTEST1 Value"
    - name: ENVTEST2
      value: "This is ENVTEST2 Value"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
