apiVersion: v1
kind: Pod
metadata:
  name: init-container
  labels:
    name: init-container
spec:
  containers:
  - name: nginx
    image: nginx
  initContainers:
  - name: install
    image: busybox
    command: ["/bin/sh","-c","sleep 10"]
