apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constrain
spec:
  limits:
    - type: Pod
      min:
        cpu: 500m
        memory: 5Mi
      max:
        cpu: "2"
        memory: 2Gi
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 10Gi
    - type: Container
      default:
        cpu: "1"
        memory: 2Gi
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      max:
        cpu: "1"
        memory: 2Gi
      min:
        cpu: 500m
        memory: 1Gi
      maxLimitRequestRatio:
        cpu: "2"
        memory: "2"