apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mongodb
  name: mongodb
spec:
  containers:
  - image: mongo
    name: mongodb
    resources: {}
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: admin
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: admin 
    # livenessProbe:
    #   exec:
    #     command:
    #       - mongo
    #       - --eval
    #       - "db.adminCommand('ping')"
    #   initialDelaySeconds: 1
    #   periodSeconds: 10
    #   timeoutSeconds: 5
    #   successThreshold: 1
    #   failureThreshold: 2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
