apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb-ns
  name: myweb-ns
spec:
  ports:
  - name: 80-32000
    port: 32000
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: myweb
  type: NodePort
status:
  loadBalancer: {}
