apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    type: backend
  name: nginx
spec:
  affinity:
    nodeAffinity:  
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
            - backend
            - frontend
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
