apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
  labels:
    name: mypod
spec:
  nodeSelector:
    size: Large
  containers:
    - name: busybox
      image: busybox
      command:
        - sleep
        - '3600'
      resources:
        limits:
          memory: 1Gi
          cpu: 500m
    - name: nginx
      image: nginx:1.7.9
      command:
        - sleep
        - '3600'
      resources:
        limits:
          memory: 1Gi
          cpu: 500m
      ports:
        - containerPort: 80