apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespacequota
  namespace: default
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "10"
    secrets: "10"
    configmaps: "10"
    services: "10"
    services.loadbalancers: "2"
    services.nodeports: "2"
    replicationcontrollers: "5"
    persistentvolumeclaims: "4"
