apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  - name: date
    image: busybox
    command: ["sh"]
    args: ["-c", "while true; do echo $(date) >> /var/log/dates.txt ; sleep 1; done"]
    volumeMounts:
    - name: logs
      mountPath: /var/log
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: httpd
    image: httpd
    volumeMounts:
    - name: logs
      mountPath: /usr/local/apache2/htdocs/
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
