apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  clusterIP: None
  ports:
  - port: 32000
    targetPort: 80

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: naginx-cont
        image: nginx
        ports:
        - containerPort: 80


