apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: configamp-pod1
  name: configamp-pod1
spec:
  volumes:
  - name: configvol
    configMap:
      name: log-config
      items:
      - key: log_level
        path: log_level
  containers:
  - image: busybox
    name: configamp-pod1
    command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
    volumeMounts:
    - mountPath: /etc/config
      name: configvol
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
