apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hostpathvol
  name: hostpathvol
spec:
  volumes:
  - name: hostvol
    hostPath:
      path: /data/foo
      type: DirectoryOrCreate
  containers:
  - image: nginx
    name: hostpathvol
    resources: {}
    command: [ '/bin/sh', '-c', 'while sleep 10; do echo $(date) >> /usr/data/index.html; done;' ]
    ports:
    - containerPort: 80
    volumeMounts:
    - name: hostvol
      mountPath: /usr/data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-ns
  name: my-ns
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32000
  selector:
    app: hostpathvol
  type: NodePort
status:
  loadBalancer: {}
