apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32000
    protocol: TCP
  type: NodePort

# kubectl port-forward svc/mongodbsvc 32000:27017