apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-vol
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: local-storage
  storageClassName: normal
  hostPath:
    path: /data
